// =============================================
// THEME TOKENS
// =============================================
export const themes = {
  light: {
    page:        'bg-cream text-[#2F3E46]',
    header:      'bg-white/95 border-border shadow-[0_4px_20px_rgba(243,239,233,0.5)]',
    logo:        'text-primary font-black tracking-tight',
    logoSub:     'text-secondary font-bold',
    headerIcon:  'bg-cream border-2 border-border rounded-2xl',
    headerIconLit:'bg-primary text-white shadow-md shadow-primary/20 scale-105 rounded-2xl',
    pill:        'bg-white border-2 border-border text-gray-700 font-bold',
    streakOff:   'bg-white border-2 border-border text-muted font-bold',
    streakOn:    'bg-accent/20 border-2 border-accent text-secondary font-black',
    logoutBtn:   'bg-white hover:bg-danger/10 text-muted hover:text-danger border-2 border-border hover:border-danger/30 btn-squish transition-all duration-200',
    toggleBtn:   'bg-white hover:bg-cream text-gray-600 border-2 border-border btn-squish transition-all duration-200',
    card:        'bg-white border-2 border-border hover:border-primary shadow-[0_8px_30px_rgb(243,239,233,0.3)] hover:shadow-[0_12px_40px_rgb(243,239,233,0.6)] rounded-[2rem] transition-all duration-300',
    sectionCard: 'bg-white border-2 border-border shadow-[0_8px_30px_rgb(243,239,233,0.3)] rounded-[2rem]',
    sectionTitle:'text-gray-800 font-black tracking-tight',
    sectionSub:  'text-muted font-medium',
    addBtn:      'bg-gradient-to-r from-primary to-[#74C69D] hover:from-[#74C69D] hover:to-accent text-white shadow-md btn-squish rounded-2xl transition-all duration-200',
    filterActive:'bg-primary text-white shadow-md btn-squish rounded-full',
    filterIdle:  'bg-white text-muted border-2 border-border hover:border-primary hover:text-primary btn-squish rounded-full',
    statSegar:   { on: 'bg-[#EAFDF8] border-2 border-success text-success shadow-md shadow-success/5 scale-[1.02]',   off: 'bg-white border-2 border-border hover:border-primary text-muted transition-all duration-200' },
    statWaspada: { on: 'bg-[#FFF9E6] border-2 border-warning text-warning shadow-md shadow-warning/5 scale-[1.02]',   off: 'bg-white border-2 border-border hover:border-primary text-muted transition-all duration-200' },
    statKritis:  { on: 'bg-[#FFEAEA] border-2 border-danger text-danger shadow-md shadow-danger/5 scale-[1.02]',     off: 'bg-white border-2 border-border hover:border-primary text-muted transition-all duration-200' },
    statBusuk:   { on: 'bg-[#F4F1EC] border-2 border-muted text-[#5C677D] shadow-md scale-[1.02]',                       off: 'bg-white border-2 border-border hover:border-primary text-muted transition-all duration-200' },
    ingCard:     'bg-white border-2 border-border hover:border-primary shadow-[0_8px_30px_rgb(243,239,233,0.3)] hover:-translate-y-1 hover:shadow-lg rounded-3xl transition-all duration-300',
    cookedBadge: 'bg-primary/10 text-primary border-2 border-primary/20 rounded-xl',
    qtyBox:      'bg-primary border-2 border-primary rounded-full shadow-sm',
    qtyText:     'text-white font-mono font-bold',
    qtyMinus:    'text-white/80 hover:text-white font-bold',
    qtyPlus:     'text-white/80 hover:text-white font-bold',
    healthBg:    'bg-[#F3EFE9] h-2.5 rounded-full',
    healthText:  'text-muted font-bold',
    editBtn:     'text-muted hover:text-primary font-bold transition-all duration-200',
    cookBtn:     'bg-gradient-to-r from-secondary to-accent hover:from-accent hover:to-secondary text-white shadow-md btn-squish rounded-xl transition-all duration-200',
    wasteBtn:    'bg-cream hover:bg-danger/10 text-muted hover:text-danger border border-border hover:border-danger/20 rounded-xl btn-squish transition-all duration-200',
    deleteBtn:   'bg-cream text-muted hover:text-danger hover:bg-danger/10 border border-border hover:border-danger/20 rounded-xl btn-squish transition-all duration-200',
    divider:     'border-border',
    emptyBox:    'bg-white border-2 border-border text-muted rounded-3xl p-8',
    fireWidget:  { on: 'bg-white border-2 border-accent shadow-md rounded-[2.5rem]', off: 'bg-white border-2 border-border rounded-[2.5rem]' },
    fireRing:    { on: 'border-accent bg-accent/10 shadow-lg shadow-accent/10 scale-105 rounded-full p-6', off: 'border-border bg-cream rounded-full p-6' },
    fireLabel:   'text-secondary font-black tracking-wider',
    streakNum:   'text-gray-800 font-black',
    fireOnMsg:   'text-primary font-bold',
    fireOffMsg:  'text-warning font-bold',
    igniteBtn:   'bg-gradient-to-r from-secondary to-accent hover:from-accent hover:to-secondary text-white rounded-xl shadow-md btn-squish transition-all duration-200',
    levelBox:    'bg-cream border-2 border-border rounded-2xl',
    levelLabel:  'text-secondary font-black',
    levelOn:     'bg-accent/20 border-2 border-accent text-secondary scale-105 rounded-xl font-black shadow-sm',
    levelOff:    'bg-white border-2 border-border text-muted rounded-xl font-bold',
    shopCard:    'bg-white border-2 border-border shadow-[0_8px_30px_rgb(243,239,233,0.3)] rounded-[2rem]',
    shopInner:   'bg-cream border-2 border-border rounded-2xl',
    shopIcon:    'bg-white border-2 border-accent shadow-sm rounded-2xl',
    shopTitle:   'text-gray-800 font-extrabold',
    shopSub:     'text-muted font-medium',
    shopXp:      'text-secondary font-black',
    shopBtnOn:   'bg-gradient-to-r from-primary to-[#74C69D] text-white hover:from-[#74C69D] hover:to-accent shadow-md btn-squish rounded-xl transition-all duration-200',
    shopBtnOff:  'bg-white border border-border text-muted cursor-not-allowed rounded-xl',
    questCard:   'bg-white border-2 border-border shadow-[0_8px_30px_rgb(243,239,233,0.3)] rounded-[2rem]',
    questTitle:  'text-gray-800 font-black',
    questItem:   { done: 'bg-cream border-2 border-border opacity-60 rounded-2xl', todo: 'bg-cream border-2 border-border hover:border-primary rounded-2xl transition-all duration-255' },
    questDesc:   'text-gray-700 font-bold',
    questXp:     'text-secondary font-extrabold',
    questDone:   'bg-[#EAFDF8] text-success border-2 border-success/30 rounded-xl font-bold',
    questClaim:  'bg-gradient-to-r from-secondary to-accent hover:from-accent hover:to-secondary text-white shadow-md btn-squish rounded-xl font-bold transition-all duration-200',
    questLock:   'bg-white text-muted border border-border cursor-not-allowed rounded-xl font-bold',
    simCard:     'bg-white border-2 border-border shadow-sm rounded-[2rem]',
    simLabel:    'text-primary font-black',
    simBtn:      'bg-cream hover:bg-accent/20 text-secondary border-2 border-accent hover:border-secondary btn-squish rounded-xl font-bold transition-all duration-200',
    modal:       'bg-white border-2 border-border rounded-[2.5rem] shadow-2xl',
    modalTitle:  'text-gray-800 font-black tracking-tight',
    modalSub:    'text-muted font-medium',
    modalClose:  'text-muted hover:text-gray-800 transition-colors',
    modalInput:  'bg-[#F8F7F2] border-2 border-border text-gray-800 placeholder:text-muted focus:border-primary focus:ring-4 focus:ring-primary/10 rounded-2xl transition-all duration-200',
    modalLabel:  'text-gray-700 font-bold',
    modalCancel: 'bg-cream hover:bg-[#F3EFE9] text-gray-700 border-2 border-border rounded-xl btn-squish transition-all duration-200',
    modalSubmit: 'bg-gradient-to-r from-primary to-secondary hover:from-secondary hover:to-primary text-white shadow-md btn-squish rounded-xl transition-all duration-200',
    modalOverlay:'bg-black/10 backdrop-blur-sm',
    toast:       'bg-white border-2 border-accent text-secondary rounded-2xl shadow-lg',
    footer:      'border-t-2 border-border bg-white text-muted font-semibold',
    healthSegar:  { color: 'text-success bg-[#EAFDF8] border-2 border-success/20 font-bold',   bar: 'bg-success' },
    healthWaspada:{ color: 'text-warning bg-[#FFF9E6] border-2 border-warning/20 font-bold',   bar: 'bg-warning' },
    healthKritis: { color: 'text-danger bg-[#FFEAEA] border-2 border-danger/20 font-bold',      bar: 'bg-danger animate-pulse' },
    healthBusuk:  { color: 'text-muted bg-[#F4F1EC] border-2 border-border font-bold',          bar: 'bg-[#8E9AAF]' },
  },
  dark: {
    page:        'bg-[#121714] text-[#F5F5F4]',
    header:      'bg-[#1B221F]/95 border-[#34413B] shadow-sm',
    logo:        'text-[#7BAE7F] font-black tracking-tight',
    logoSub:     'text-[#A3B18A] font-bold',
    headerIcon:  'bg-[#222B27] border-2 border-[#34413B] rounded-2xl',
    headerIconLit:'bg-[#7BAE7F] text-[#121714] shadow-md scale-105 rounded-2xl',
    pill:        'bg-[#222B27] border-2 border-[#34413B] text-[#F5F5F4] font-bold',
    streakOff:   'bg-[#222B27] border-2 border-[#34413B] text-[#B8C1BA] font-bold',
    streakOn:    'bg-[#7BAE7F]/15 border-2 border-[#7BAE7F]/50 text-[#7BAE7F] font-black',
    logoutBtn:   'bg-[#1B221F] hover:bg-[#222B27] text-[#B8C1BA] hover:text-[#D8C3A5] border-2 border-[#34413B] btn-squish transition-all duration-200',
    toggleBtn:   'bg-[#222B27] hover:bg-[#34413B] text-[#F5F5F4] border-2 border-[#34413B] btn-squish transition-all duration-200',
    card:        'bg-[#1B221F] border-2 border-[#34413B] hover:border-[#7BAE7F]/50 shadow-sm rounded-[2rem] transition-all duration-350',
    sectionCard: 'bg-[#1B221F] border-2 border-[#34413B] shadow-sm rounded-[2rem]',
    sectionTitle:'text-[#F5F5F4] font-black tracking-tight',
    sectionSub:  'text-[#B8C1BA] font-medium',
    addBtn:      'bg-gradient-to-r from-[#7BAE7F] to-[#A3B18A] hover:from-[#A3B18A] hover:to-[#D8C3A5] text-[#121714] shadow-sm btn-squish rounded-xl transition-all duration-200',
    filterActive:'bg-[#7BAE7F] text-[#121714] shadow-md btn-squish rounded-full',
    filterIdle:  'bg-[#1B221F] text-[#B8C1BA] border-2 border-[#34413B] hover:border-[#7BAE7F]/50 hover:text-[#7BAE7F] btn-squish rounded-full',
    statSegar:   { on: 'bg-[#7BAE7F]/15 border-2 border-[#7BAE7F] text-[#7BAE7F] shadow-sm scale-[1.02]', off: 'bg-[#1B221F] border-2 border-[#34413B] hover:border-[#7BAE7F]/50 text-[#B8C1BA] transition-all duration-200' },
    statWaspada: { on: 'bg-[#D8C3A5]/15 border-2 border-[#D8C3A5] text-[#D8C3A5] shadow-sm scale-[1.02]', off: 'bg-[#1B221F] border-2 border-[#34413B] hover:border-[#D8C3A5]/50 text-[#B8C1BA] transition-all duration-200' },
    statKritis:  { on: 'bg-[#C44536]/15 border-2 border-[#C44536] text-[#C44536] shadow-sm scale-[1.02]', off: 'bg-[#1B221F] border-2 border-[#34413B] hover:border-[#C44536]/50 text-[#B8C1BA] transition-all duration-200' },
    statBusuk:   { on: 'bg-[#C44536]/15 border-2 border-[#C44536] text-[#C44536] shadow-sm scale-[1.02]', off: 'bg-[#1B221F] border-2 border-[#34413B] hover:border-[#C44536]/50 text-[#B8C1BA] transition-all duration-200' },
    ingCard:     'bg-[#1B221F] border-2 border-[#34413B] hover:border-[#7BAE7F]/50 shadow-sm hover:-translate-y-1 hover:shadow-lg rounded-3xl transition-all duration-300',
    cookedBadge: 'bg-[#7BAE7F]/15 text-[#7BAE7F] border-2 border-[#7BAE7F]/30 rounded-xl',
    qtyBox:      'bg-[#7BAE7F] border-2 border-[#7BAE7F] rounded-full shadow-sm',
    qtyText:     'text-[#121714] font-mono font-bold',
    qtyMinus:    'text-[#121714]/70 hover:text-[#121714] font-bold',
    qtyPlus:     'text-[#121714]/70 hover:text-[#121714] font-bold',
    healthBg:    'bg-[#34413B] h-2.5 rounded-full',
    healthText:  'text-[#B8C1BA] font-bold',
    editBtn:     'text-[#B8C1BA] hover:text-[#7BAE7F] font-bold transition-all duration-200',
    cookBtn:     'bg-gradient-to-r from-[#7BAE7F] to-[#A3B18A] hover:from-[#A3B18A] hover:to-[#D8C3A5] text-[#121714] shadow-md btn-squish rounded-xl transition-all duration-200',
    wasteBtn:    'bg-[#222B27] hover:bg-[#C44536]/15 text-[#B8C1BA] hover:text-[#C44536] border border-[#34413B] rounded-xl btn-squish transition-all duration-200',
    deleteBtn:   'bg-[#222B27] text-[#B8C1BA] hover:text-[#C44536] hover:bg-[#C44536]/15 border border-[#34413B] rounded-xl btn-squish transition-all duration-200',
    divider:     'border-[#34413B]',
    emptyBox:    'bg-[#1B221F] border-2 border-[#34413B] text-[#B8C1BA] rounded-3xl p-8',
    fireWidget:  { on: 'bg-[#1B221F] border-2 border-[#7BAE7F]/40 shadow-sm rounded-[2.5rem]', off: 'bg-[#1B221F] border-2 border-[#34413B] rounded-[2.5rem]' },
    fireRing:    { on: 'border-[#7BAE7F] bg-[#7BAE7F]/10 shadow-lg shadow-[#7BAE7F]/10 scale-105 rounded-full p-6', off: 'border-[#34413B] bg-[#222B27] rounded-full p-6' },
    fireLabel:   'text-[#7BAE7F] font-black',
    streakNum:   'text-[#F5F5F4] font-black',
    fireOnMsg:   'text-[#7BAE7F] font-bold',
    fireOffMsg:  'text-[#D8C3A5] font-bold',
    igniteBtn:   'bg-gradient-to-r from-[#7BAE7F] to-[#A3B18A] hover:from-[#A3B18A] hover:to-[#D8C3A5] text-[#121714] rounded-xl shadow-md btn-squish transition-all duration-200',
    levelBox:    'bg-[#1B221F] border-2 border-[#34413B] rounded-2xl',
    levelLabel:  'text-[#7BAE7F] font-black',
    levelOn:     'bg-[#7BAE7F]/15 border-2 border-[#7BAE7F] text-[#7BAE7F] scale-105 rounded-xl font-black shadow-sm',
    levelOff:    'bg-[#222B27] border-2 border-[#34413B] text-[#B8C1BA] rounded-xl font-bold',
    shopCard:    'bg-[#1B221F] border-2 border-[#34413B] shadow-sm rounded-[2rem]',
    shopInner:   'bg-[#222B27] border-2 border-[#34413B] rounded-2xl',
    shopIcon:    'bg-[#1B221F] border-2 border-[#7BAE7F]/40 shadow-sm rounded-2xl',
    shopTitle:   'text-[#F5F5F4] font-extrabold',
    shopSub:     'text-[#B8C1BA] font-medium',
    shopXp:      'text-[#7BAE7F] font-black',
    shopBtnOn:   'bg-gradient-to-r from-[#7BAE7F] to-[#A3B18A] text-[#121714] hover:from-[#A3B18A] hover:to-[#D8C3A5] shadow-md btn-squish rounded-xl transition-all duration-200',
    shopBtnOff:  'bg-[#222B27] border border-[#34413B] text-[#B8C1BA] cursor-not-allowed rounded-xl',
    questCard:   'bg-[#1B221F] border-2 border-[#34413B] shadow-sm rounded-[2rem]',
    questTitle:  'text-[#F5F5F4] font-black',
    questItem:   { done: 'bg-[#222B27] border-2 border-[#34413B] opacity-60 rounded-2xl', todo: 'bg-[#222B27] border-2 border-[#34413B] hover:border-[#7BAE7F]/45 rounded-2xl' },
    questDesc:   'text-[#F5F5F4] font-bold',
    questXp:     'text-[#7BAE7F] font-extrabold',
    questDone:   'bg-[#7BAE7F]/15 text-[#7BAE7F] border border-[#7BAE7F]/30 rounded-xl font-bold',
    questClaim:  'bg-gradient-to-r from-[#7BAE7F] to-[#A3B18A] hover:from-[#A3B18A] hover:to-[#D8C3A5] text-[#121714] shadow-md btn-squish rounded-xl font-bold transition-all duration-200',
    questLock:   'bg-[#222B27] text-[#B8C1BA] border border-[#34413B] cursor-not-allowed rounded-xl font-bold',
    simCard:     'bg-[#1B221F] border-2 border-[#34413B] shadow-sm rounded-[2rem]',
    simLabel:    'text-[#7BAE7F] font-black',
    simBtn:      'bg-[#222B27] hover:bg-[#34413B] text-[#7BAE7F] border-2 border-[#34413B] hover:border-[#7BAE7F] btn-squish rounded-xl font-bold transition-all duration-200',
    modal:       'bg-[#1B221F] border-2 border-[#34413B] rounded-[2.5rem] shadow-2xl',
    modalTitle:  'text-[#F5F5F4] font-black tracking-tight',
    modalSub:    'text-[#B8C1BA] font-medium',
    modalClose:  'text-[#B8C1BA] hover:text-[#F5F5F4] transition-colors',
    modalInput:  'bg-[#222B27] border-2 border-[#34413B] text-[#F5F5F4] placeholder:text-[#B8C1BA] focus:border-[#7BAE7F] focus:ring-4 focus:ring-[#7BAE7F]/10 rounded-2xl transition-all duration-200',
    modalLabel:  'text-[#F5F5F4] font-bold',
    modalCancel: 'bg-[#222B27] hover:bg-[#34413B] text-[#F5F5F4] rounded-xl border-2 border-[#34413B] btn-squish transition-all duration-200',
    modalSubmit: 'bg-gradient-to-r from-[#7BAE7F] to-[#A3B18A] hover:from-[#A3B18A] hover:to-[#D8C3A5] text-[#121714] shadow-md btn-squish rounded-xl transition-all duration-200',
    modalOverlay:'bg-black/50 backdrop-blur-sm',
    toast:       'bg-[#1B221F] border-2 border-[#7BAE7F]/40 text-[#7BAE7F] rounded-2xl shadow-lg',
    footer:      'border-t-2 border-[#34413B] bg-[#1B221F] text-[#B8C1BA] font-semibold',
    healthSegar:  { color: 'text-[#7BAE7F] bg-[#7BAE7F]/15 border-2 border-[#7BAE7F]/20 font-bold',   bar: 'bg-[#7BAE7F]' },
    healthWaspada:{ color: 'text-[#D8C3A5] bg-[#D8C3A5]/15 border-2 border-[#D8C3A5]/20 font-bold',   bar: 'bg-[#D8C3A5]' },
    healthKritis: { color: 'text-[#C44536] bg-[#C44536]/15 border-2 border-[#C44536]/20 font-bold',      bar: 'bg-[#C44536] animate-pulse' },
    healthBusuk:  { color: 'text-[#B8C1BA] bg-[#222B27] border-2 border-[#34413B] font-bold',          bar: 'bg-[#34413B]' },
  },
};
