import client from './client'
export const getIngredients       = ()              => client.get('/ingredients')
export const addIngredient        = (data)          => client.post('/ingredients', data)
export const updateIngredient     = (id, data)      => client.put(`/ingredients/${id}`, data)
export const adjustQuantity       = (id, dir)       => client.put(`/ingredients/${id}/adjust`, { direction: dir })
export const cookIngredient       = (id)            => client.post(`/ingredients/${id}/cook`)
export const cookAmountIngredient = (id, amount)    => client.post(`/ingredients/${id}/cook-amount`, { amount })
export const cookBatchIngredients = (items)         => client.post('/ingredients/cook-batch', { items })
export const wasteIngredient      = (id, amount)    => client.patch(`/ingredients/${id}/waste`, { amount })
export const deleteIngredient     = (id)            => client.delete(`/ingredients/${id}`)